# Generated by Django 5.0 on 2024-01-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomgenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RanNums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=5)),
                ('my_list', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rangenmodel',
            name='stake',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rangenmodel',
            name='win',
            field=models.IntegerField(null=True),
        ),
    ]
